name: Checks

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

env:
  NODE_OPTIONS: '--no-warnings'
  NEXT_TELEMETRY_DISABLED: '1'
  ACTIONS_RUNNER_DEBUG: true

jobs:
  checks:
    if: ${{ !contains(github.event.head_commit.message, '[skip-checks]') }}
    timeout-minutes: 3
    runs-on: ['ubuntu-latest']
    steps:
      - name: '🔑 Checkout'
        uses: actions/checkout@v4.1.1

      - name: '🐰 Setup Bun'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: 'Setup Biome'
        uses: biomejs/setup-biome@v1
        with:
          version: 'latest'

      - name: '🧹 Lint'
        run: biome ci .

      - name: '📦 Install Dependencies'
        run: bun install --frozen-lockfile

      - name: '🧪 Typecheck'
        run: bun typecheck

      - name: '🔧 Build'
        run: bun run build
