name: Checks

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  checks:
    if: ${{ !contains(github.event.head_commit.message, '[skip-checks]') }}
    timeout-minutes: 3
    runs-on: ['ubuntu-latest']
    steps:
      - name: 🔑 Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: '📦 Install Dependencies'
        run: bun install

      - name: '🧹 Lint'
        run: bun lint

      - name: '🧹 Format'
        run: bun format

      - name: '🧪 Typecheck'
        run: bun typecheck

      - name: '🔧 Build'
        run: bun build
