name: Checks

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

env:
  NODE_OPTIONS: '--no-warnings'
  NEXT_TELEMETRY_DISABLED: '1'
  ACTIONS_RUNNER_DEBUG: true

jobs:
  checks:
    uses: ethereumfollowprotocol/actions/.github/workflows/checks.yml@main
    with:
      bun-version: 'latest'
      install-dependencies: true
      skip-steps: 'test'
